### ISSUE TITLE
关于珠子无法解锁的问题

### ISSUE THREAD

**Issue by SBliu-1** [bocai-bca/mhw_no_story_save#1]
该存档似乎无法解锁珠子的穿脱，我只能从总司令那里领取珠子，但是没找到穿脱的选项，我使用的是无等级的存档。

**Comment by bocai-bca** [comment]
这个问题曾有人在B站反馈过，但是我在自己和周围朋友的设备上未能复现。
看到此issue后我再次装入了一个全新的无主线档尝试，和总司令对话过后虽然拿到了珠子，但是确认了会仍看不到"穿脱饰品"选项，也没有护石槽。但我发现在与月辰的加工屋的第二期团团长对话第二次后，他会给玩家一个珠子，在我这里解锁了"穿脱饰品"选项，至此我设备上似乎属于*解决了此问题*。
目前对于这个问题我手中没有更多的线索可以深入，你可以尝试一下去找他对话，如果解决了此问题请回来汇报哦，或者如果问题仍存在也可提供更多线索。
